_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 63
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 63
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
cfg_weight:
    value: 5
checkpoint_path:
    value: /home/v-haodongli/mnt/v-haodongli-container_doch/haodongli/janus-SFT/checkpoint-20000/unwrapped_model
image_token_num_per_image:
    value: 576
max_new_tokens:
    value: 200
parallel_size:
    value: 16
prompt_file:
    value: Image-Generation-CoT/geneval/prompts/generation_prompts.txt
temperature:
    value: 0.5
